[2023-06-11T01:52:37.513+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2021-10-02T07:00:00+00:00 [queued]>
[2023-06-11T01:52:37.519+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2021-10-02T07:00:00+00:00 [queued]>
[2023-06-11T01:52:37.520+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-11T01:52:37.520+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-06-11T01:52:37.521+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-11T01:52:37.528+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-10-02 07:00:00+00:00
[2023-06-11T01:52:37.532+0000] {standard_task_runner.py:54} INFO - Started process 8117 to run task
[2023-06-11T01:52:37.535+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data', 'download_dataset_task', 'scheduled__2021-10-02T07:00:00+00:00', '--job-id', '797', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_multiFile_v02.py', '--cfg-path', '/tmp/tmp98szjmpu']
[2023-06-11T01:52:37.536+0000] {standard_task_runner.py:83} INFO - Job 797: Subtask download_dataset_task
[2023-06-11T01:52:37.537+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs_multiFile_v02.py
[2023-06-11T01:52:37.595+0000] {data_ingestion_gcs_multiFile_v02.py:20} INFO - dtc_data_lake_dtc-dezc-001 is the bucket.
[2023-06-11T01:52:37.610+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-11T01:52:37.650+0000] {task_command.py:384} INFO - Running <TaskInstance: fhv_taxi_data.download_dataset_task scheduled__2021-10-02T07:00:00+00:00 [running]> on host f41d61956f54
[2023-06-11T01:52:37.672+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-11T01:52:37.698+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=fhv_taxi_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-02T07:00:00+00:00
[2023-06-11T01:52:37.699+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T01:52:37.700+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2021-10.csv.gz > /opt/***/fhv_tripdata_2021-10.csv.gz']
[2023-06-11T01:52:37.710+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T01:52:37.945+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 404
[2023-06-11T01:52:37.951+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2023-06-11T01:52:37.974+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2023-06-11T01:52:37.979+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=fhv_taxi_data, task_id=download_dataset_task, execution_date=20211002T070000, start_date=20230611T015237, end_date=20230611T015237
[2023-06-11T01:52:37.994+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 797 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 8117)
[2023-06-11T01:52:38.044+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-11T01:52:38.065+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
